#config_version=6

#Normal Skillshot to the upper rollovers
#Full/soft plunge to the scoop/
#Left or right flipper activation causes dropper ramp to drop and activate super skillshot either 3 bank, pop bumper or lower long target. 
#Which will reward, locks, bonus ball saver timer, spot xenos, big points, bonus x, light mystery, extra ball, 

mode:
  start_events: ball_started, skillshot_restart
  stop_events: 
    - skill_shot_success
    - skill_shot_failed
  priority: 500
shots:
    skill_xenos_x:
        switch: s_xenos_x
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_xenos_x
    skill_xenos_e:
        switch: s_xenos_e
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_xenos_e
    skill_xenos_n:
        switch: s_xenos_n
        profile: skill_shot_profile
        # advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_xenos_n
    skill_xenos_o:
        switch: s_xenos_o
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_xenos_o
    skill_xenos_s:
        switch: s_xenos_s
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_xenos_s

    skill_left_inlane:
        switch: s_left_inlane
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_warp_a
    skill_right_inlane:
        switch: s_right_inlane
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_warp_r
    skill_right_outlane:
        switch: s_right_outlane
        profile: skill_shot_profile
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          light: l_warp_r
    
    skill_lowerloop:
        switch: s_lowerloop

    skill_necron:
        switch: s_right_outlane

    super_skillshot:
        switch: s_necron_target
        profile: super_skill_shot_profile
        start_enabled: false
        #advance_events: mode_skill_shot_started        # replace "skill_shot" with your mode name
        show_tokens:
          skillshotlight1: l_solemnace_circle
          skillshotlight2: l_solemnace_arrow
          skillshotlight3: l_necron_lock1
          skillshotlight4: l_necron_lock2
          skillshotlight_color: green

    double_super_skillshot:
        switch: s_jackpot_vuk
        profile: double_super_skill_shot_profile
        start_enabled: false
        show_tokens:
          skillshotlight1: l_pop_flasher
          skillshotlight2: l_jackpot
          skillshotlight3: l_jackpot
          skillshotlight4: l_super_jackpot
          skillshotlight_color: green
        
sequence_shots: 
    super_skill_necron_combo:
        switch_sequence:
          - s_lowerloop
          - s_left_inlane
          - s_necron_target

    double_super_skillshot_combo:
        switch_sequence:
          - s_right_orbit
          - s_innerloop_right
          - s_innerloop_right
          - s_jackpot_vuk

sequences: 

    super_skillshot_selected:
        reset_on_complete: false
        enable_events: super_skill_shot_option
        disable_events: super_skill_shot_disabled
        events:
          - s_left_flipper_active
          - s_autoplunger_inactive
        events_when_complete:
          - enable_superskillshot


shot_groups:
  skill_shot_group:
    shots: skill_xenos_x, skill_xenos_e, skill_xenos_n, skill_xenos_o, skill_xenos_s
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active

  super_skill_shot_group:
    shots: super_skillshot
    enable_events: enable_superskillshot

  double_super_skill_shot_group:
    shots: double_super_skillshot
    enable_events: enable_superskillshot


shot_profiles:
  skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: flash
  super_skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: skillshot_light_show
        speed: 10
  double_super_skill_shot_profile:
    advance_on_hit: false
    states: 
      - name: lit
        show: super_skillshot_light_show
        speed: 10

timers:
  skill_shot_timeout:
    start_value: 0
    end_value: 10     # set the timeout of your skill shot here
    direction: up
    tick_interval: 1s
    start_running: false
    control_events:
      - action: start
        event: balldevice_bd_plunger_ball_eject_success  # replace "plunger_lane" with the name of your plunger device

show_player: 
    enable_superskillshot_lights: 
        skillshot_light_show:
            action: play
            speed: 10
            show_tokens:
              skillshotlight1: l_solemnace_circle
              skillshotlight2: l_solemnace_arrow
              skillshotlight3: l_necron_lock1
              skillshotlight4: l_necron_lock2
              skillshotlight_color: green

        super_skillshot_light_show:
            action: play
            speed: 10
            show_tokens:
              skillshotlight1: l_right_orbit_cicle
              skillshotlight2: l_right_orbit_arrow
              skillshotlight3: l_left_innerloop_arrow
              skillshotlight4: l_right_innerloop_circle
              skillshotlight5: l_innerloop_arrow
              skillshotlight6: l_innerloop_flasher
              skillshotlight7: l_left_innerloop_arrow
              skillshotlight8: l_pop_flasher
              skillshotlight9: l_jackpot
              skillshotlight10: l_super_jackpot
              skillshotlight_color: red

    reset_superskillshot_droptarget:
        skillshot_light_show:
            action: stop
        super_skillshot_light_show:
            action: stop
            
    super_skill_necron_combo_hit:
        necron_rings:
            action: play
            loops: 6
            speed: 40
        skillshot_light_show:
            action: stop

event_player:
    # only trigger the lights and drop if the sequence has not been picked 
    # aka its a pre-show to prompt the player
    s_left_flipper_active{device.sequences.super_skillshot_selected.enabled == False}: 
        - enable_superskillshot_lights
        - super_skill_shot_option
    s_left_flipper_inactive{device.sequences.super_skillshot_selected.enabled == True and device.switches.s_autoplunger.state == 1}:
        - reset_superskillshot_droptarget
        - super_skill_shot_disabled
    
    super_skill_necron_combo_hit:
        - skill_shot_success|3s
        #we reset the drop target if the player did not take the super skillshot, false would mean the sequence was triggered and its now disabled
    double_super_skillshot_combo_hit:
        - skill_shot_success|3s
    
coil_player: 
    s_left_flipper_active: c_droptarget_down
    s_left_flipper_inactive: c_droptarget_reset
        
                        
sound_player:
    super_skill_necron_combo_hit:
        trayzn_super_skillshot:
            volume: 2
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    double_super_skillshot_combo_hit:
        trayzn_double_super_skillshot:
            volume: 2
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    
    