#config_version=6
##! mode: warp_qualify

mode:
  #this mode starts when the ball starts
  start_events: ball_started
  stop_events: rewardbank_mode_stop
  priority: 200

shots:
  rewardbank_lightlock:
    switch: s_light_lock
    profile: inlane_lane_profile
    show_tokens:
      led: l_lightlock
  rewardbank_lightspinners:
    switch: s_light_spinners
    profile: inlane_lane_profile
    show_tokens:
      led: l_light_spinners
  rewardbank_bonusx:
    switch: s_bonus_x
    profile: inlane_lane_profile
    show_tokens:
      led: l_bonusx
  rewardbank_lightmystery:
    switch: s_light_mystery
    profile: inlane_lane_profile
    show_tokens:
      led: l_light_mystery

shot_groups:
  reward_bank_group:
    shots: rewardbank_lightlock, rewardbank_lightspinners, rewardbank_bonusx, rewardbank_lightmystery
    reset_events: reward_bank_group
    rotate_events: timer_rewardbank_rotation_tick

timers:
  rewardbank_rotation:
    start_value: 0
    tick_interval: 1s
    start_running: true
    control_events:
      - event: mode_WeaponsBank_started
        action: start
      - event: reward_bank_group_hit
        action: stop

shot_profiles:
    rewardbank_generic_flash:
        states:
            - name: flashing
              show: "generic_flash"
            - name: hit
              show: "on"
    rewardbank_final_shot_profile:
        states:
            - name: flashing
              show: "generic_flash"
            - name: hit
              show: "on"
        loop: false

variable_player:
  inlane_lane_group_hit_complete:
    score: 100000
    bonus_multiplier: 1
    weapons_bank_value: 
      action: add
      int: 100000


event_player:
  timer_rewardbank_rotation_tick:
    - rotate_rewardbank  
  rewardbank_lightlock_hit:
    - start_mode_lock_mode
    - stop_mode_rewardbank
  rewardbank_lightspinners_hit:
    - start_mode_spinners_mode
    - stop_mode_rewardbank
  rewardbank_bonusx_hit:
    - start_mode_bonus_mode
    - stop_mode_rewardbank
  rewardbank_lightmystery_hit:
    - start_mode_mystery_mode
    - stop_mode_rewardbank
    


