#config_version=6

mode:
  start_events: ModeSelect_nurgle_selected
  stop_events: timer_khorne_mode_timer_complete
  priority: 200

 # The Plague Lord (Number 7): The number 7
#Ring the bells of nurgle 
#Ring 7 Bells to finish nurgle in order
# first shot scores 4, 7, 10 ,15 and final is 20 million 
# each right spinner rip scores 1 million and adds 500k to the next shot 
# hitting 3 shots lights ally 

timers:
    nurgle_mode_timer: 
        start_value: 60 # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true
