#config_version=6

mode:
  start_events: start_mission_select
  stop_events: mission_select_item_selected, mission_select_item_cancelled
  code: mpf.modes.carousel.code.carousel.Carousel
  events_when_stopped: mission_select_item_selected
  game_mode: true
  priority: 1501

mode_settings:
  selectable_items: 
    - khorne
    - nurgle
    - slannesh 
    - tzeench 
    - necrons
    - backToTheFight
  select_item_events: s_start_button_active
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
    item_highlighted: mission_select
    mode_mission_select_started: mission_select

sound_player:
    mode_mission_select_started: 
        choose_a_mission:
           action: play
           volume: 1
           bus: voice
           ducking:
               bus: music
               attack: 0.3 sec
               attenuation: 0
               release_point: 2.0 sec
               release: 1.0 sec