#config_version=5
mode:
  start_events: ball_started
  priority: 100

show_player:
  mode_base_started:
   base_light_show:
    speed: 1

variable_player:
  s_right_inlane_active:
    score: 1000
  s_left_inlane_active:
    score: 1000
  s_right_outlane_active:
    score: 1000
  s_left_outlane_active:
    score: 1000
  s_left_slingshot_active:
    score: 500
  s_right_slingshot_active:
    score: 500

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50