#config_version=6

sound_player:
    enable_mystery:
        Mystery_award_available:
            action: play
            volume: 1
            bus: voice
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    mystery_achieved:
        Mystery_awards_pool:
            action: play
            volume: 1
            ducking:
                bus: voice
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    mode_base_started: 
        Admonition:
            action: play
            volume: 0.7
            bus: music
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    play_welcome_instruction: 
        WelcomeBattleBrother2:
            action: play
            volume: 1
            bus: voice
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    play_howto_instruction: 
        hurryUpAndMystery:
            action: play
            volume: 1
            bus: voice
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    waagh_multiball_start:
        Rise_of_the_WAAAGH:
            action: play
            bus: music
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
        Admonition:
            action: stop
            bus: music

            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    left_drain_hit:
        big-ben:
            action: play
            volume: 2
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_left_slingshot_active:
        slingshots:
            action: play
            volume: 2
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_right_slingshot_active:
        slingshots:
            action: play
            volume: 2
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
      #center ramp
    s_center_ramp_active:
        DP_Cinematic_SFX_Stinger_Impact Aware_01:
            action: play
            volume: 2
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_left_orbit_active:
        DP_Cinematic_SFX_Ramp_Enter_Chungus_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_droptarget_lock_active:
        DP_Cinematic_SFX_Drop Target_Clankle Dank_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    
    s_pop_top_active:
        pop_sfx:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_pop_bottom_active:
        pop_sfx:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    #lower loop
    s_lower_loop_active:
        DP_Cinematic_SFX_Stinger_Klaxxon_Klaxxoff:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
      #right orbit
    s_right_orbit_active:
        DP_Cinematic_SFX_Ramp Exit_Filtered Exit_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
            #center spinner
    spinner_center_spinner_hit:
        lazgun_sfx:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0 sec
                attenuation: 0
                release_point: 0.0 sec
                release: 0.0 sec
            #left spinner
    spinner_left_spinner_hit:
        lazgun_sfx:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
            #right spinner
    spinner_right_spinner_hit:
        lazgun_sfx:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_jackpot_vuk_active:
        DP_Cinematic_SFX_Stinger_Tarantular The Destroyer_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_snikt_target_active:
        DP_Cinematic_SFX_Standup_Plasmate_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_left_inlane_active:
        mecha-sound-impact:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    
    s_right_inlane_active:
        mecha-sound-impact:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    balldevice_bd_scoop_ejecting_ball:
        DP_Cinematic_SFX_Scoop_The Eject Sound:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    
    s_nurgle_redcircle_active:
        DP_Cinematic_SFX_Stinger_Sub Affair_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_waagh_newton_ball_active:
        DP_Cinematic_SFX_Slingshot_Atrium Sub_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    multiball_lock_titan_ball_locked:
        DP_Cinematic_SFX_Stinger_Tarantular The Destroyer_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_necron_target_active:
        DP_Cinematic_SFX_Standup_Plasmate_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_scoop_nurgle_target_active:
        DP_Cinematic_SFX_Drop Target_Thump_01:
            action: play
            volume: 1.3
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_light_lock_active:
        DP_Cinematic_SFX_Drop Target_Clankle Dank_01:
                action: play
                volume: 1.3
                ducking:
                    bus: effects
                    attack: 0.3 sec
                    attenuation: 0
                    release_point: 2.0 sec
                    release: 1.0 sec
    s_bonus_x_active:
        DP_Cinematic_SFX_Drop Target_Clankle Dank_01:
                action: play
                volume: 1.3
                ducking:
                    bus: effects
                    attack: 0.3 sec
                    attenuation: 0
                    release_point: 2.0 sec
                    release: 1.0 sec
    s_light_mystery_active:
        DP_Cinematic_SFX_Drop Target_Clankle Dank_01:
                action: play
                volume: 1.3
                ducking:
                    bus: effects
                    attack: 0.3 sec
                    attenuation: 0
                    release_point: 2.0 sec
                    release: 1.0 sec
    s_light_spinners_active:
        DP_Cinematic_SFX_Drop Target_Clankle Dank_01:
                action: play
                volume: 1.3
                ducking:
                    bus: effects
                    attack: 0.3 sec
                    attenuation: 0
                    release_point: 2.0 sec
                    release: 1.0 sec
    imperial_fists_qualified: 
        imperialFistsJoinTheBattle:
                action: play
                volume: 1.5
                ducking:
                    bus: effects
                    attack: 0.3 sec
                    attenuation: 0
                    release_point: 2.0 sec
                    release: 1.0 sec