#config_version=6
sequence_shots: 
  right_orbit:
    switch_sequence: s_right_orbit, s_innerloop_left
    sequence_timeout: 3s
  complete_inner_loop:
    switch_sequence: s_innerloop_right, s_innerloop_left, s_lowerloop
    sequence_timeout: 3s
   #Secret Combo Shots
    # Xenos Bank into the innder loop
  secret_combo_1:
    switch_sequence: s_xenos_x, s_innerloop_right, s_innerloop_left
    sequence_timeout: 3s
  secret_combo_2:
    switch_sequence: s_xenos_e, s_innerloop_right, s_innerloop_left
    sequence_timeout: 3s
  secret_combo_3:
    switch_sequence: s_xenos_n, s_innerloop_right, s_innerloop_left
    sequence_timeout: 3s
  secret_combo_4:
    switch_sequence: s_xenos_o, s_innerloop_right, s_innerloop_left
    sequence_timeout: 3s
  secret_combo_5:
    switch_sequence: s_xenos_s, s_innerloop_right, s_innerloop_left
    sequence_timeout: 3s
      # Xenos Bank into the inner loop into the jackpot vuk
  secret_combo_6:
    switch_sequence: s_xenos_x, s_innerloop_right, s_innerloop_left, s_jackpot_vuk
    sequence_timeout: 3s
  secret_combo_7:
    switch_sequence: s_xenos_e, s_innerloop_right, s_innerloop_left, s_jackpot_vuk
    sequence_timeout: 3s
  secret_combo_8:
    switch_sequence: s_xenos_n, s_innerloop_right, s_innerloop_left, s_jackpot_vuk
    sequence_timeout: 3s
  secret_combo_9:
    switch_sequence: s_xenos_o, s_innerloop_right, s_innerloop_left, s_jackpot_vuk
    sequence_timeout: 3s
  secret_combo_10:
    switch_sequence: s_xenos_s, s_innerloop_right, s_innerloop_left, s_jackpot_vuk
    sequence_timeout: 3s
