#config_version=6
variable_player:

  s_lower_bigtarget_active:
    score: 3000 * (current_player.playfield_multiplier)
  s_upper_bigtarget_active:
    score: 5000 * (current_player.playfield_multiplier)
  s_right_inlane_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_left_inlane_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_right_outlane_active:
    score: 10000 * (current_player.playfield_multiplier)
  s_left_outlane_active:
    score: 10000 * (current_player.playfield_multiplier)
  s_left_slingshot_active:
    score: 500 * (current_player.playfield_multiplier)
  s_right_slingshot_active:
    score: 500 * (current_player.playfield_multiplier)
  s_pop_left_active:
    score: 500  * (current_player.playfield_multiplier)
  s_pop_right_active:
    score: 500 * (current_player.playfield_multiplier)
  s_rollover_mork_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_rollover_gork_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_upperscoop_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_spinner_active:
    score: 100 * (current_player.playfield_multiplier)
  s_xenos_x_active:
    score: 100 * (current_player.playfield_multiplier)
  s_xenos_e_active:
    score: 100  * (current_player.playfield_multiplier)
  s_xenos_n_active:
    score: 100 * (current_player.playfield_multiplier)
  s_xenos_o_active:
    score: 100   * (current_player.playfield_multiplier)
  s_xenos_s_active:
    score: 100  * (current_player.playfield_multiplier)
  s_kickback1_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_kickback2_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_disk_backtarget_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_droptarget_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_droptarget_lock_active:
    score: 1000 * (current_player.playfield_multiplier)
  spinner_center_spinner_hit:
    score: 5000 * (current_player.playfield_multiplier)
  s_scoop_active:
    score: 1000 * (current_player.playfield_multiplier)
  s_3bank_shot_hit:
    score: 1000 * (current_player.playfield_multiplier)
  s_3bank_shot_flashProfile_flashing_hit:
    score: 10000 * (current_player.playfield_multiplier)
  s_center_ramp_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_scoop_active_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_scoop_nurgle_target_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_18_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_light_mystery_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_bonus_x_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_light_spinners_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_light_lock_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_droptarget_down_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_24_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_25_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_26_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_27_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_necron_target_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_right_orbit_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_nurgle_redcircle_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_right_spinner_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_dreadnought_lock1_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_dreadnought_lock2_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_dreadnought_lock3_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_jackpot_vuk_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_nurgle_ricochet_target_active:
    score: 2000 * (current_player.playfield_multiplier)
  s_waagh_newton_ball_active:
    score: 2000 * (current_player.playfield_multiplier)
  base_warp_hurry_up_hit:
    score: timer_base_hurry_up_warp_ticks
  boost_base_shot_value:
    base_shot_value: 50000
  boost_base_spinner_value: 
    base_spinner_value: 1000
