#config_version=6
##! mode: base

event_player:
  mode_base_started: warp_traveler
  mode_base_started{player==1 and ball==1}: 
    - play_welcome_instruction|2s
    - play_howto_instruction|15s

  s_left_slingshot_active: sling_hit
  s_right_slingshot_active: sling_hit
  s_scoop_active: scoop_hit
  s_spinner_active: spinner_hit
  #player_added{num == 1}: base_sound_player_1
  player_added{num == 2}: base_sound_player_2
  player_added{num == 3}: base_sound_player_3
  player_added{num == 4}: base_sound_player_4
  player_added{game.num_players == 1}: base_start_single_player, base_sound_player_1
  player_added{game.num_players == 2}: base_start_multi_player_two
  player_added{game.num_players == 3}: base_start_multi_player_three
  player_added{game.num_players == 4}: base_start_multi_player_four
  mode_base_started{game.num_players == 1}: base_start_single_player
  mode_base_started{game.num_players == 2}: base_start_multi_player_two
  mode_base_started{game.num_players == 3}: base_start_multi_player_three
  mode_base_started{game.num_players == 4}: base_start_multi_player_four
  base_skillshot_should_start: skillshot_should_start
  ball_save_default_saving_ball:
    cmd_backbox_show_overlay:
      show_type: sweep_vertical
      color: "FF2000"
      speed: 1
      repeat: 0
      direction: up
  mode_bonus_will_start: stop_all_music
  s_snikt_target_active: 
    - ork_left 
    - ork_right|.5s 
    - ork_left|.1s 
    - ork_right|1.5s
    - ork_home|2s
  # mission_select_item_selected:
  #   - play_scoop_flash_show
  #   - release_one_ball|.5s
  # mission_select_item_cancelled: 
  #   - play_scoop_flash_show
  #   - release_one_ball|.5s
  # # balldevice_bd_scoop_ball_entered:
  # #   play_scoop_flash_show
  # #   release_one_ball|.5s
  mission_select_item_selected:
    - play_scoop_flash_show
    - release_one_ball|.5s
  mission_select_item_cancelled:
    - play_scoop_flash_show
    - release_one_ball|.5s
  mystery_achieved:
    - play_scoop_flash_show
    - release_one_ball|.5s
  ball_hold_base_scoop_full:
    - play_scoop_flash_show
    - release_one_ball|.5s

  base_titan_lock_qualifier_1_hit:
    - titan_lock_qualified ##Call to mode titan qualifier 