#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_will_end
  priority: 300

event_player:
  award_light_lock: #Comes from the mystery mode event
    - enable_dreadnought_lock_shot
    - lock_open #opens lock servo, allowing the ball to enter the lock and qualify for multiball
  dreadnought_lock_qualified:
    - enable_dreadnought_lock_shot
    - lock_open #opens lock servo, allowing the ball to enter the lock and qualify for multiball

#event comes from the ball device when the lock is qualified, which is when the ball enters the lock and the lock is open. This means that the player has successfully locked a ball and qualified for multiball.
  multiball_lock_dreadnought_locked_ball{current_player.dreadnought_multiball_qualifier_lock_count == 0}: 
    - lock_home
  multiball_lock_dreadnought_locked_ball{current_player.dreadnought_multiball_qualifier_lock_count > 0}: 
    - lower_dreadnought_lock_count

  multiball_lock_dreadnought_full: 
    - start_dreadnought_multiball| 5s
    # Do Light show event here

    # Do sound effects event here







variable_player:
  award_light_lock:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: 1
  dreadnought_lock_qualified:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: 1
  lower_dreadnought_lock_count:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: -1

shots:
  dreadnought_lock:
    switch: s_dreadnought_lock1
    start_enabled: false
    profile: dreadnought_lock_profile
    restart_events: enable_dreadnought_lock_shot
    disable_events: lock_home
    show_tokens:
      shot_color: lime
      shot_led1: l_center_ramp_circle
      shot_led2: l_center_ramp_arrow


sound_player:
    multiball_lock_dreadnought_locked_ball{total_balls_locked==1}:  
        BallOneLocked:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec
    multiball_lock_dreadnought_locked_ball{total_balls_locked==2}:   
        BallTwoLocked:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec
    multiball_lock_dreadnought_full:
        DreadnoughtMultiballVoice:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec
        

shot_profiles:
  dreadnought_lock_profile:
    states:
      - name: lit
        show: generic_flash #Lock profile Light show
        speed: 10
        loops: -1

show_player:
  dreadnought_lock_qualified:
    2toneflash:
     action: play
     loops : 1
     speed: 50
     show_tokens:
        even_color: blue
        odd_color: gold

  multiball_lock_dreadnought_locked_ball: 
    2toneflash:
     action: play
     loops : 1
     speed: 50
     show_tokens:
        even_color: blue
        odd_color: gold



    