#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_will_end
  priority: 300

event_player:
  award_light_lock: #Comes from the mystery mode event
    - enable_dreadnought_lock_shot
    - lock_open #opens lock servo, allowing the ball to enter the lock and qualify for multiball
  dreadnought_lock_qualified:
    - enable_dreadnought_lock_shot
    - lock_open #opens lock servo, allowing the ball to enter the lock and qualify for multiball

#event comes from the ball device when the lock is qualified, which is when the ball enters the lock and the lock is open. This means that the player has successfully locked a ball and qualified for multiball.
  multiball_lock_dreadnought_locked_ball{current_player.dreadnought_multiball_qualifier_lock_count == 0}: 
    - lock_home
  multiball_lock_dreadnought_locked_ball{current_player.dreadnought_multiball_qualifier_lock_count > 0}: 
    - lower_dreadnought_lock_count

  multiball_lock_dreadnought_full: 
    - dreadnought_multiball_intro
  timer_dreadnought_multiball_intro_complete:
    - dreadnought_multiball_intro_complete







variable_player:
  award_light_lock:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: 1
  dreadnought_lock_qualified:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: 1
  lower_dreadnought_lock_count:
    dreadnought_multiball_qualifier_lock_count:
      action: add
      int: -1

shots:
  dreadnought_lock:
    switch: s_dreadnought_lock1
    start_enabled: false
    profile: dreadnought_lock_profile
    restart_events: enable_dreadnought_lock_shot
    disable_events: lock_home
    show_tokens:
      shot_color: lime
      shot_led1: l_center_ramp_circle
      shot_led2: l_center_ramp_arrow


sound_player:
    dreadnought_awaken_show:
        404443:
            action: play 
            volume: 1 
            ducking: 
                bus: voice
                attack: 0.1 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    multiball_lock_dreadnought_locked_ball{total_balls_locked==1}:  
        BallOneLocked:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec
    multiball_lock_dreadnought_locked_ball{total_balls_locked==2}:   
        BallTwoLocked:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec
    dreadnought_multiball_intro:
        DreadnoughtMultiballVoice:
            action: play
            volume: 1
            ducking:
                bus: music
                attack: 0.3 sec
                attenuation: -30
                release_point: 2.0 sec
                release: 1.0 sec

timers:
    dreadnought_multiball_intro:
        start_value: 8
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: false
        restart_on_complete: false
        control_events:
            - event: dreadnought_multiball_intro
              action: restart

queue_event_player:
    multiball_lock_dreadnought_full:
        queue_event: dreadnought_multiball_intro_queue
        events_when_finished: start_dreadnought_multiball

queue_relay_player:
    dreadnought_multiball_intro_queue:
        post: dreadnought_multiball_intro
        wait_for: dreadnought_multiball_intro_complete

slide_player:
    dreadnought_multiball_intro:
        dreadnought_multiball_intro
    dreadnought_multiball_intro_complete:
        dreadnought_multiball_intro:
            action: remove
        

shot_profiles:
  dreadnought_lock_profile:
    states:
      - name: lit
        show: generic_flash #Lock profile Light show
        speed: 10
        loops: -1

show_player: 
  dreadnought_awaken_show: 
    set_GI:
     action: play
     loops: -1
     speed: 1
     show_tokens: 
        led: GI
        color: red
    dreadnought_awaken_light_show:
     action: play 
     loops: -1
     speed: 
     show_tokens: 
       shot_led1: dreadnought1
       shot_led2: dreadnought2
       shot_color: yellow 
       
  

  dreadnought_lock_qualified:
    2toneflash:
     action: play
     loops : 1
     speed: 50
     show_tokens:
        even_color: blue
        odd_color: gold

  dreadnought_multiball_intro:
    dreadnought_awaken:
      action: play
      loops: 1
      show_tokens:
        led: dreadnought

  dreadnought_multiball_intro_complete:
    dreadnought_awaken:
      action: stop

  multiball_lock_dreadnought_locked_ball: 
    2toneflash:
     action: play
     loops : 1
     speed: 50
     show_tokens:
        even_color: blue
        odd_color: gold



    