#config_version=5
show_player:
  xenos_x_complete:
    light_xenos_letter:
      priority: 10
      key: xenos_x_hit_show
      show_tokens:
        gadget_letter_made_led: l_xenos_x
        gadget_letter_made_color: yellow
        gadget_letter_final_color: yellow
  xenos_e_complete:
    light_xenos_letter:
      priority: 10
      key: xenos_e_hit_show
      show_tokens:
        gadget_letter_made_led: l_xenos_e
        gadget_letter_made_color: yellow
        gadget_letter_final_color: yellow
  xenos_n_complete:
    light_xenos_letter:
      priority: 10
      key: xenos_n_hit_show
      show_tokens:
        gadget_letter_made_led: l_xenos_n
        gadget_letter_made_color: yellow
        gadget_letter_final_color: yellow
  xenos_o_complete:
    light_xenos_letter:
      priority: 10
      key: xenos_o_hit_show
      show_tokens:
        gadget_letter_made_led: l_xenos_o
        gadget_letter_made_color: yellow
        gadget_letter_final_color: yellow
  xenos_s_complete:
    light_xenos_letter:
      priority: 10
      key: xenos_s_hit_show
      show_tokens:
        gadget_letter_made_led: l_xenos_s
        gadget_letter_made_color: yellow
        gadget_letter_final_color: yellow
  reset_xenos_lights:
    light_xenos_letter:
      priority: 10
      show_tokens:
        gadget_letter_made_led: xenos_letter
        gadget_letter_made_color: yellow
        gadget_letter_final_color: 000000