#config_version=6
##! mode: xenos

config:
  - logic_blocks.yaml
  - event_player.yaml
  - show_player.yaml

mode:
  #this mode starts when the ball starts
  start_events: ball_started
  priority: 200


#sound_player:
#   s_xenos_x_active: 
#       xenos_hit_fx:
#           action: play
#           bus: sfx
#   s_xenos_e_active:   
#       xenos_hit_fx:
#           action: play
#           bus: sfx
#   s_xenos_n_active:    
#       xenos_hit_fx:
#           action: play
#           bus: sfx
#   s_xenos_o_active:     
#       xenos_hit_fx:
#           bus: sfx
#   s_xenos_s_active:      
#       xenos_hit_fx:
#           bus: sfx
#   xenos_spotted: 
#        xenos-spotted: 
#            bus: voice

