#config_version=6
##! mode: bonus

mode:
  start_events: ball_ending     # start on ball ending process
  use_wait_queue: true          # delay ball ending
  priority: 500                 # determines the order of ball end modes
  stop_events: stop_bonus_mode     # post this event to stop the mode and continue the ball ending process


mode_settings:
  display_delay_ms: 2s
  bonus_entries:
    - entry: bonus_relics
      score: 100000* (current_player.holy_relics) 
    - entry: bonus_switches
      score:   100000* (current_player.switch_hits )
    - entry: bonus_warps
      score: 100000* (current_player.warp_jumps) 

slide_player:
  mode_bonus_started: bonus

widget_player:
  bonus_entries: bonus_entries_widget
  bonus_relics: bonus_total_widget
  bonus_switches: bonus_total_widget
  bonus_warps: bonus_warp_count
  bonus_total: bonus_total_widget

event_player:
    bonus_warps: 
        bonus_total
    