#config_version=6

mode:
  start_events: ModeSelect_tzeench_selected
  stop_events: timer_tzeench_mode_timer_complete
  priority: 200

timers:
    tzeench_mode_timer: 
        start_value: 60 # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true

counters: 

    
    center_tzeench_spinner:
        count_events: s_center_spinner
        starting_count: 50
        count_interval: 1
        count_complete_value: 100
    left_tzeench_spinner:
        count_events: s_left_spinner
        starting_count: 0
        count_interval: 1
        count_complete_value: 30
    right_tzeench_spinner: 
        count_events: s_right_spinner
        starting_count: 0
        count_interval: 1
        count_complete_value: 50

event_player:
    center_tzeench_spinner_complete: 
        s_tempholder1_active
    left_tzeench_spinner_complete:
        s_tempholder2_active
    right_tzeench_spinner_complete:
        s_tempholder3_active
#config_version=6
##! mode: xenos
accruals:
  tzeench_accrual:
    events:
      - center_spinner_shot_completed # index [0]
      - left_spinner_shot_completed # index [1]
      - right_spinner_shot_completed # index [2]
    reset_on_complete: false
    disable_on_complete: true 
    events_when_complete: award_tzeench_mode_complete 

shots:
    center_spinner_shot:
        switch: s_tempholder1
        profile: generic_flash
        show_tokens:
             light: l_center_ramp_arrow
    left_spinner_shot:
        switch: s_tempholder2
        profile: generic_flash
        show_tokens:
             light: l_left_orbit_arrow
    right_spinner_shot:
        switch: s_tempholder3
        profile: generic_flash
        show_tokens:
             light: l_right_orbit_arrow
# Make a false switch entry and then user the counters
# complete to throw the switch hit logic that ends the shot and rewards completing each shot

shot_groups:
    tzeench_spinners:
        shots: 
            - center_spinner_shot
            - left_spinner_shot
            - right_spinner_shot
        enable_events: ball_started
        disable_events: ball_ending

shot_profiles:
    generic_flash:
        states:
            - name: unlit
              show: off
            - name: lit
              show: "flash"
            - name: hit
              show: "on"


