#config_version=6
##! mode: bonus

mode_settings:
  bonus_entries:
    - entry: bonus_switches
      text: "Switches Hit"
      score: (current_player.switch_hits )
    - entry: bonus_holy_relics
      text: "Holy Relics Collected"
      score: (current_player.holy_relics) * (current_player.holy_relic_value)
    - entry: bonus_modes_started
      text: "Battles Started"
      score: 750000
      player_score_entry: current_player.modes_started
    - entry: bonus_warpjumps
      text: "Warp Jumps Made"
      score: 150000
      player_score_entry: current_player.warp_jumps