#config_version=5

mode:
  start_events: ball_started
  stop_events:  stop_mode_gorkmorkrollovers


shots: 
  top_lane_gork:
    switch: s_rollover_gork
    profile: top_lane_profile
    show_tokens: 
      rollover_made_led: l_gork
      rollover_made_color: yellow
      rollover_made_final_color: cyan
  top_lane_mork:
    switch: s_rollover_mork
    profile: top_lane_profile
    show_tokens: 
      rollover_made_led: l_mork
      rollover_made_color: yellow
      rollover_made_final_color: cyan

shot_profiles:
  top_lane_profile:
    states:
      - name: 
        show: off
      - name: hit
        show: "light_gorkmork"
        
shot_groups:
  top_lane_group:
    shots: top_lane_gork, top_lane_mork
    reset_events: top_lane_group_hit_complete
    rotate_right_events: s_flipper_right_active
    rotate_left_events: s_flipper_left_active

variable_player:
  top_lane_group_hit_complete:
    score: 10000
    bonus_multiplier: 1