#config_version=6

mode:
  start_events: ball_started
  priority: 300

accruals:
  waagh_accrual:
    events:
      - waagh_qualify_shot_w_complete # index [0]
      - waagh_qualify_shot_a_complete # index [0]- warp_a_complete # index [1]
      - waagh_qualify_shot_a2_complete # index [0]- warp_r_complete # index [2]
      - waagh_qualify_shot_g_complete # index [0]- warp_p_complete # index [3]
      - waagh_qualify_shot_h_complete # index [0]- warp_p_complete # index [3]
      - waagh_qualify_shot_exc_complete # index [0]- warp_p_complete # index [3]
    reset_on_complete: false
    disable_on_complete: true
    reset_events: mode_warp_qualify_started
    events_when_complete: reset_waagh_lights, waagh_multiball_mode_start

event_player:
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==False}: 
        - waagh_qualify_shot_w_complete
        - waagh_qualify_shot_a_enable
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==True and device.accruals.waagh_accrual.value[1]==False}:
        - waagh_qualify_shot_a_complete
        - waagh_qualify_shot_a2_enable
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==True and device.accruals.waagh_accrual.value[1]==True and device.accruals.waagh_accrual.value[2]==False}:
        - waagh_qualify_shot_a2_complete
        - waagh_qualify_shot_g_enable
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==True and device.accruals.waagh_accrual.value[1]==True and device.accruals.waagh_accrual.value[2]==True and device.accruals.waagh_accrual.value[3]==False}:
        - waagh_qualify_shot_g_complete
        - waagh_qualify_shot_h_enable
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==True and device.accruals.waagh_accrual.value[1]==True and device.accruals.waagh_accrual.value[2]==True and device.accruals.waagh_accrual.value[3]==True and device.accruals.waagh_accrual.value[4]==False}:  
        - waagh_qualify_shot_h_complete
        - waagh_qualify_shot_exc_enable
        - waagh_face_enable
    s_waagh_newton_ball_active{device.accruals.waagh_accrual.value[0]==True and device.accruals.waagh_accrual.value[1]==True and device.accruals.waagh_accrual.value[2]==True and device.accruals.waagh_accrual.value[3]==True and device.accruals.waagh_accrual.value[4]==True and device.accruals.waagh_accrual.value[5]==False }:
        - waagh_qualify_shot_exc_complete
    mode_waagh_qualifier_started:
      - waagh_qualify_shot_w_enable
    
show_player:
  waagh_face_enable:
      light_waagh_shot:
        priority: 20
        key: waagh_face
        loops: -1
        show_tokens:
          show_led: waagh_face
          show_led_color: Yellow
          show_led_color_final_color: Yellow
  waagh_qualify_shot_w_enable:
    light_waagh_shot:
      priority: 30
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_W
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_a_enable:
    light_waagh_shot:
      priority: 20
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_A
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_a2_enable:
    light_waagh_shot:
      priority: 20
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_A2
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_g_enable:
    light_waagh_shot:
      priority: 20
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_G
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_h_enable:
    light_waagh_shot:
      priority: 20
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_H
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_exc_enable:
    light_waagh_shot:
      priority: 20
      key: waagh_lit
      loops: -1
      show_tokens:
        show_led: l_waagh_!
        show_led_color: Red
        show_led_color_final_color: Red
  waagh_qualify_shot_w_complete:
    light_waagh_letter:
      priority: 10
      key: waagh_w_hit_show
      show_tokens:
        show_led: l_waagh_W
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_a_complete:
    light_waagh_letter:
      priority: 10
      key: waagh_a_hit_show
      show_tokens:
        show_led: l_waagh_A
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_a2_complete:
    light_waagh_letter:
      priority: 10
      key: waagh_a2_hit_show
      show_tokens:
        show_led: l_waagh_A2
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_g_complete:
    light_waagh_letter:
      priority: 10
      key: xenos_o_hit_show
      show_tokens:
        show_led: l_waagh_G
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_h_complete:
    light_waagh_letter:
      priority: 10
      key: xenos_s_hit_show
      show_tokens:
        show_led: l_waagh_H
        show_led_color: Yellow
        show_led_color_final_color: Yellow
  waagh_qualify_shot_exc_complete:
    light_waagh_letter:
      priority: 10
      show_tokens:
        show_led: l_waagh_!
        show_led_color: Red
        show_led_color_final_color: Red
  reset_waagh_lights:
    light_waagh_letter:
      priority: 20
      show_tokens:
        show_led: waagh_letter, waagh_face
        show_led_color: Yellow
        show_led_color_final_color: 000000
