#config_version=5
mode:
  start_events: start_necron_multiball
  stop_events: multiball_necron_multiball_ended
  priority: 100
multiballs:
  necron_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 20s
    start_events: start_necron_multiball
    ball_locks: bd_necron_lock