#config_version=6
mode:
  start_events: start_necron_multiball
  stop_events: ball_will_end, multiball_necron_multiball_ended
  priority: 100
  
multiballs:
  necron_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    stop_events: ball_will_end
    ball_locks: bd_necron_lock
    start_events:
      - start_necron_multiball

sound_player:
  mode_necron_multiball_started:
    Nightsider:
      action: play
      volume: 1.3
      bus: music
      ducking:
        bus: effects
        attack: 0.3 sec
        attenuation: 0
        release_point: 2.0 sec
        release: 1.0 sec