# mode multiball
##! mode: multiball
mode:
  start_events: multiball_lock_necron_lock_full
  stop_events: multiball_necron_multiball_ended
multiballs:
  necron_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 20s
    start_events: start_necron_multiball
    ball_locks: bd_necron_lock