#config_version=5
mode:
  start_events: multiball_lock_necron_lock_full
  stop_events: ball_will_end
  priority: 100
  
multiballs:
  necron_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 20s
    start_events: start_necron_multiball
    stop_events: ball_will_end
    ball_locks: bd_necron_lock