#config_version=6
mode:
  start_events: multiball_lock_necron_lock_full
  stop_events: ball_will_end
  priority: 100
  
multiballs:
  necron_multiball:
    ball_count: 2
    ball_count_type: total
    shoot_again: 10s
    start_events: s_droptarget_down_active
    stop_events: ball_will_end
    ball_locks: bd_necron_lock