#config_version=6
##! mode: mechanicus_qualifier


mode:
  #this mode starts when the ball starts
  start_events: award_warp
  priority: 20


shots:
  mechanicus_scoop_shot:
    switch: s_scoop
    profile: generic_flash_profile
    start_enabled: true
    show_tokens:
      led: l_adeptus_mechanicius

shot_profiles:
  generic_flash_profile:
    states:
      - name: unlit
        show: off
      - name: lit
        show: generic_flash
        show_tokens:
          color: yellow

event_player:
  ball_hold_mystery_scoop_held_ball: start_mechanicus_mode
  mechanicus_scoop_shot_lit_hit: mechanicus_scoop_shot_complete
  
accruals:
  mechanicus_accrual:
    events:
      - mechanicus_scoop_shot_complete # index [0]
    reset_on_complete: false
    disable_on_complete: true
    reset_events: mode_warp_qualify_started
    events_when_complete: start_mechanicus_mode


ball_holds:
  mystery_scoop:
    balls_to_hold: 1
    hold_devices: bd_scoop
    enable_events: mode_ModeSelect_enable_started
    disable_events: mode_ModeSelect_enable_stopping
    release_one_events: ModeSelect_item_selected