#config_version=6
##! mode:super_jets
mode: 
    start_events: enable_super_jets, re-enable_super_jets
    stop_events: ball_ending 
    priority: 300

variable_player: 
    mode_super_jets_started:
        sj_active: 1
        action: set
    s_jet_bottom_active:
        score: 100000|block 
    s_jet_top_active:
        score: 100000|block

widget_player:
  mode_super_jets_started:
    super_jets:
      action: play
      slide: base
      x: 38.25
      y: 10.5
      priority: 300

show_player:
  mode_super_jets_started:
    super_jets:
      action: play
      speed: 15
      loops: -1
      show_tokens:
        led: bottom_jet_flasher, top_jet_flasher
        color: white

sound_player:
    mode_super_jets_started:
        super_jets_callout:
            action: play
            volume: 1.9
            bus: voice
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec

    s_jet_top_active:
        pop_sfx:
            action: play
            volume: 1.4
            bus: sfx
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec
    s_jet_bottom_active:
        pop_sfx:
            action: play
            volume: 1.4 
            bus: sfx
            ducking:
                bus: effects
                attack: 0.3 sec
                attenuation: 0
                release_point: 2.0 sec
                release: 1.0 sec