#config_version=6

coils:
  c_trough_eject:
    number: 3208-1
    default_pulse_ms: 14
  c_autoplunger:
    number: 3208-0
    default_pulse_ms: 12
  c_left_slingshot:
    number: 3208-6
    default_pulse_ms: 5
    allow_enable: true
  c_right_slingshot:
    number: 3208-3
    default_pulse_ms: 5
    allow_enable: true
  c_flipper_left_main:
    number: 3208-4  # again, these numbers will probably be different for you
    default_pulse_ms: 27
  c_flipper_left_hold:
    number: 3208-5  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    default_pulse_ms: 27
    number: 3208-2
  c_flipper_right_hold:
    number: 3208-7
    allow_enable: true
  c_pop_top:
    number: 32082-0
    default_pulse_ms: 17
  c_pop_bottom:
    number: 32082-2
    default_pulse_ms: 17
  c_uppost:
    number: 32082-5
    default_pulse_ms: 17
  c_upperscoop:
    number: 32082-3
    default_pulse_ms: 8
  c_droptarget_reset:
    number: 32082-4
    default_pulse_ms: 18
  c_scoop:
    number: 32082-1

  c_droptarget_smartdrop:
    number: 32082-7
  c_droppod:
    number: 32082-6
    default_pulse_ms: 18
    #default_pulse_ms: 200
    #
    default_hold_power: 0.250
    allow_enable: true
  c_flipper_upperleft_main:
    default_pulse_ms: 12
    number: io0804-0
  c_flipper_upperleft_hold:
    number: io0804-1
    allow_enable: true



#digital_outputs:
#  c_liftramp: 
#    number: 32082-6
#    type: driver

#motors:
#  motorized_drop_target_bank:
#    motor_left_output: c_liftramp
##    position_switches: 
  #    up: s_dropramp_home
   #   down: s_dropramp_away
    #reset_position: up
    #go_to_position:
    #  go_up: up
     # go_down: down

    ##enable_event: warp_mode_enable
    ##disable_event: 