#config_version=6

coils:
  c_trough_eject:
    number: 3208-7
    default_pulse_ms: 14
  c_autoplunger:
    number: 3208-6
    default_pulse_ms: 12
  c_right_slingshot:
    number: 3208-2
    default_pulse_ms: 5
    allow_enable: true
  c_left_slingshot:
    number: 3208-0
    default_pulse_ms: 5
    allow_enable: true
  c_flipper_left_main:
    number: 3208-4  # again, these numbers will probably be different for you
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 3208-5  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    default_pulse_ms: 20
    number: 3208-1
  c_flipper_right_hold:
    number: 3208-3
    allow_enable: true
  c_pop_left:
    number: 32082-0
    default_pulse_ms: 17
  c_pop_center:
    number: 32082-1
    default_pulse_ms: 17
  c_pop_right:
    number: 32082-2
    default_pulse_ms: 17
  c_upperscoop:
    number: 32082-3
    default_pulse_ms: 3
  c_droptarget_reset:
    number: 32082-4
    default_pulse_ms: 18
  c_scoop:
    number: 32082-5
  c_tron_disk:
    number: 32082-6
    allow_enable: true
    enable_events: mode_warp_started
    disable_events: timer_warp_timer_complete
  c_flipper_upperleft_main:
    default_pulse_ms: 12
    number: io0804-0
  c_flipper_upperleft_hold:
    number: io0804-1
    allow_enable: true



digital_outputs:
  c_3bank: 
    number: 32082-7
    type: driver

motors:
  motorized_drop_target_bank:
    motor_left_output: c_3bank
    position_switches: 
      up: s_3bank_home
      down: s_3bank_away
    reset_position: up
    go_to_position:
      go_up: up
      go_down: down

    ##enable_event: warp_mode_enable
    ##disable_event: 