#config_version=6
# This config is only valid for MPF 0.56.1

hardware:
    platform: fast 

fast:

  net:
    controller: neuron
    io_loop: 
            3208:
                model: FP-I/O-3208
                order: 3
            32082:
                model: FP-I/O-3208
                order: 1
            io0804:
                model: FP-I/O-0804
                order: 2
    baud: 921600
    debug: false
    console_log: none
    file_log: basic
    watchdog: 1s
    default_quick_debounce_open: 1ms
    default_quick_debounce_close: 1ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    #port: com5
    boards: 
      playfield:
        model: FP-EXP-0081
        led_fade_time: 100ms
      neuron:
        model: FP-EXP-2000

game: 
  balls_per_game: 3
 
machine: 
  balls_installed: 6
  min_balls: 0
  
config: 
  - lights.yaml
  - coils.yaml
  - flippers.yaml
  - switches.yaml
  - videos.yaml
  - timed_switches.yaml
  - assets.yaml
  - sounds.yaml
  - player_variables.yaml
  - sound_system.yaml
  - drop_targets.yaml


displays:
  window:
    width: 1920
    height: 1080
    default: true
    #fullscreen: true

window:
  height: 1080
  width: 1920
  title: Mission Pinball Framework
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true
  source_display: window

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

ball_devices:
    bd_plunger:
      mechanical_eject: True
      ball_switches: s_autoplunger
      eject_coil: c_autoplunger
      eject_timeouts: 19s
      eject_targets: playfield
    bd_trough:
      ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
      eject_coil: c_trough_eject
      tags: trough, home, drain
      jam_switch: s_trough_jam
      eject_coil_jam_pulse: 15ms
      eject_targets: bd_plunger
      eject_timeouts: 3s
      debug: true

    bd_upperscoop:
      ball_switches: s_upperscoop
      eject_coil: c_upperscoop
      eject_timeouts: 3s

    bd_lowerscoop:
      ball_switches: s_scoop
      eject_coil: c_scoop
      eject_timeouts: 3s 

    bd_left_vuk:
        ball_switches: s_left_vuk
        eject_coil: c_droppod
        eject_timeouts: 3s

    bd_right_vuk:
        ball_switches: s_left_orbit
        eject_coil: c_upperscoop
        eject_timeouts: 3s
    #bd_necron_lock:
    #  mechanical_eject: Trues
    #  ball_switches: s_droptarget_opto

    bd_droppod:
      mechanical_eject: false
      ball_switches: s_lockopto1, s_lockopto2, s_lockopto3
      eject_coil: c_droppod
      eject_timeouts: 3s
      

ball_holds:
  lowerScoop: 
    balls_to_hold: 1
    hold_devices: bd_lowerscoop
    disable_events: mode_nurgle_started, mode_khorne_started, mode_tzeench_started, mode_slannesh_started
    enable_events: carousel_qualified, mode_nurgle_ended, mode_khorne_ended, mode_tzeench_ended, mode_slannesh_ended
    release_one_events: carousel_item_selected, carousel_item_cancelled 

autofire_coils:
  ac_slingshot_left:
    coil: c_left_slingshot
    switch: s_left_slingshot
  ac_slingshot_right:
    coil: c_right_slingshot
    switch: s_right_slingshot
  #ac_popbumper_left:
  #  coil: c_pop_left
  #  switch: s_pop_left
  #ac_popbumper_center:
  #  coil: c_pop_center
  #  switch: s_pop_center
  #ac_popbumper_right:
  #  coil: c_pop_right
  #  switch: s_pop_right

slide_player:
    mode_base_started: base
    #init_done: welcome_slide
    #mode_attract_started: attract


machine_vars:
    grandChampion_1_label:
        initial_value: 'THE EMPORERS CHOSEN'
        value_type: str
        persist: true
    highScore1_label: 
        initial_value: "HIGH SCORE #1"
        value_type: str
    highScore2_label: 
        initial_value: "HIGH SCORE #2"
        value_type: str
    highScore3_label:
        initial_value: "HIGH SCORE #3"
        value_type: str
    highScore4_label:        
        initial_value: "HIGH SCORE #4"
        value_type: str
    grandChampion_name:
        initial_value: guilliman
        persist: true
        value_type: str
    highScore1_name: 
        initial_value: Horus
        value_type: str
        persist: true
    highScore2_name:
        initial_value: Horus
        value_type: str
        persist: true
    highScore3_name: 
        initial_value: Horus
        value_type: str
        persist: true
    highScore4_name:
        initial_value: Horus
        value_type: str
        persist: true
    grandChampion_value: 
        initial_value: 1000004
        persist: true
    highScore1_value: 
        initial_value: 1000004
        persist: true
    highScore2_value:
        initial_value: 1000004
        persist: true
    highScore3_value: 
        initial_value: 1000004
        persist: true
    highScore4_value: 
        initial_value: 1000004
        persist: true
    
    
shot_profiles: 
  my_first_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash
      - name: lit
        show: on
    loop: true


virtual_platform_start_active_switches:
  #- s_trough1
  #- s_trough2
  #- s_trough3

modes: 
  - base
  #- high_score
  - xenos
  - warp
  - nurgle
  - khorne
  - tzeench
  - slannesh
  #- waagh_multiball
  #- inquisition_multiball
  #- horus
  - tilt  
  - bonus
  #- necron_lock
  #- necron_lock_qualified
  #- necron_multiball
  - gorkmorkrollovers
  #- skillshot
  #- super_skillshot



