#config_version=5
# This config is only valid for MPF 0.56.1

hardware:
    platform: fast 

fast:
  net:
    port: com4
    controller: neuron
    io_loop: 
            3208:
                model: FP-I/O-3208
                order: 1
            3208_2:
                model: FP-I/O-3208
                order: 2 
    baud: 921600
    debug: false
    console_log: none
    file_log: basic
    watchdog: 1s
    default_quick_debounce_open: 1ms
    default_quick_debounce_close: 1ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    port: com5
    boards: 
      playfield:
        model: FP-EXP-0081
        led_fade_time: 100ms
      neuron:
        model: FP-EXP-2000
  
lights:
  GI_light1:
    number: playfield-1-1
  GI_light2:
    number: playfield-1-2
  GI_light3:
    number: playfield-1-3
  GI_light4: 
    number: playfield-1-4
  GI_light5:
    number: playfield-1-5
  GI_light6:
    number: playfield-1-6
  GI_light7:
    number: playfield-1-7
  GI_light8:
    number: playfield-1-8
  GI_light9:
    number: playfield-1-9


switches:
  s_trough_jam:
    number: 3208-17
  s_trough1:
    number: 3208-1
  s_trough2:
    number: 3208-2
  s_trough3:
    number: 3208-3
  s_trough4:
    number: 3208-4
  s_trough5:
    number: 3208-5
  s_trough6:
    number: 3208-7
  s_spinner:
    number: 3208-6
    debounce: quick
  s_start_button:
    number: 3208-30
    tags: start
  s_right_outlane:
    number: 3208-8
    #tags: playfield_active
  s_right_inlane:
    number: 3208-9
    #tags: playfield_active
  s_left_flipper: 
    number: 3208-31 
    tags: left_flipper
  s_right_slingshot: 
    number: 3208-10
  s_right_EOS:
    number: 3208-11
  s_left_EOS:
    number: 3208-12
  s_left_inlane:
    number: 3208-14
    tags: playfield_active
  s_left_outlane: 
    number: 3208-15
    tags: playfield_active
  s_left_slingshot: 
    number: 3208-13

  s_right_flipper:
    number: 3208-29 
    tags: right_flipper
  s_autoplunger:
    number: 3208-0
  s_pop_left:
    number: 3208-19
  s_pop_right:
    number: 3208-20
  s_pop_center:
    number: 3208-21
  s_rollover_gork:
    number: 3208-22
  s_rollover_mork: 
    number: 3208-23
  s_upperscoop:
    number: 3208-18
    

coils:
  c_trough_eject:
    number: 3208-7
    default_pulse_ms: 12
  c_autoplunger:
    number: 3208-6
    default_pulse_ms: 12
  c_right_slingshot:
    number: 3208-2
    default_pulse_ms: 10
    allow_enable: true
  c_left_slingshot:
    number: 3208-0
    default_pulse_ms: 10
    allow_enable: true
  c_flipper_left_main:
    number: 3208-4  # again, these numbers will probably be different for you
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 3208-5  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    default_pulse_ms: 20
    number: 3208-1
  c_flipper_right_hold:
    number: 3208-3
    allow_enable: true
  c_pop_left:
    number: 3208_2-0
    default_pulse_ms: 12
  c_pop_center:
    number: 3208_2-1
    default_pulse_ms: 12
  c_pop_right:
    number: 3208_2-2
    default_pulse_ms: 12
  c_upperscoop:
    number: 3208_2-3
    default_pulse_ms: 3

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    #enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    #enable_events: machine_reset_phase_3

ball_devices:
    bd_plunger:
      mechanical_eject: false
      ball_switches: s_autoplunger
      eject_coil: c_autoplunger
      eject_timeouts: 5s
      eject_targets: playfield
    bd_trough:
      ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
      eject_coil: c_trough_eject
      tags: trough, home, drain
      jam_switch: s_trough_jam
      eject_coil_jam_pulse: 15ms
      eject_targets: bd_plunger
      eject_timeouts: 3s
      debug: true

    bd_upperscoop:
      ball_switches: s_upperscoop
      eject_coil: c_upperscoop
      eject_timeouts: 3s

autofire_coils:
  ac_slingshot_left:
    coil: c_left_slingshot
    switch: s_left_slingshot
  ac_slingshot_right:
    coil: c_right_slingshot
    switch: s_right_slingshot
  ac_popbumper_left:
    coil: c_pop_left
    switch: s_pop_left
  ac_popbumper_center:
    coil: c_pop_center
    switch: s_pop_center
  ac_popbumper_right:
    coil: c_pop_right
    switch: s_pop_right
  

slides: 
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL BITCH!
        font_size: 60
        color: red
      - type: rectangle
        width: 460
        height: 60
  attract_started: 
    widgets:
      - text: ATTRACT MODE
        type: text 

slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started


keyboard:
  z:
    switch: s_left_flipper
  "<":
    switch: s_right_flipper
  x:
    switch: s_trough1
    toggle: true
  c:
    switch: s_trough2
    toggle: true
  v:
    switch: s_trough3
    toggle: true
  b:
    switch: s_trough4
    toggle: true
  n:
    switch: s_trough5
    toggle: true
  m: 
    switch: s_trough6
    toggle: true
  s:
    switch: s_start_button
  o:
    switch: s_right_outlane

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

modes: 
  - base