#config_version=5
# This config is only valid for MPF 0.56.1

hardware:
    platform: fast 

fast:
  net:
    port: com4
    controller: neuron
    io_loop: 
            3208:
                model: FP-I/O-3208
                order: 1
    baud: 921600
    debug: false
    console_log: none
    file_log: basic
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    port: com5
    boards: 
      playfield:
        model: FP-EXP-0081
        led_fade_time: 100ms
      neuron:
        model: FP-EXP-2000
  
lights:
      GI_light1:
        number: playfield-1-1
      GI_light2:
        number: playfield-1-2
      GI_light3:
        number: playfield-1-3
      GI_light4: 
        number: playfield-1-4
      GI_light5:
	number: playfield-1-5
     # l_led3:
      #  number: expansion1-1-2
    #GI_light3:
    #  number: playfield-1-1


switches:
  s_trough_jam:
    number: 3208-23
  s_trough1:
    number: 3208-25
  s_trough2:
    number: 3208-26
  s_trough3:
    number: 3208-28
  s_trough4:
    number: 3208-16
  s_trough5:
    number: 3208-24
  s_trough6:
    number: 3208-27
  s_start_button:
    number: 3208-30
    tags: start
  s_right_outlane:
    number: 3208-8
    tags: playfield_active
  s_right_inlane:
    number: 3208-9
    tags: playfield_active
  s_left_flipper: 
    number: 3208-31 
    tags: left_flipper
  s_right_slingshot: 
    number: 3208-10
  s_right_EOS:
    number: 3208-11
  s_left_EOS:
    number: 3208-12
  s_left_inlane:
    number: 3208-14
    tags: playfield_active
  s_left_outlane: 
    number: 3208-15
    tags: playfield_active
  s_left_slingshot: 
    number: 3208-13

  s_right_flipper:
    number: 3208-29 
    tags: right_flipper
  s_plunger_lane:
    number: 3208-0 
  s_shooter_lane:
    number: 3208-1

coils:
  c_trough_eject:
    number: 3208-7
  knocker:
    number: 3208-6
  c_right_slingshot:
    number: 3208-2
    default_pulse_ms: 10
    allow_enable: true
  c_left_slingshot:
    number: 3208-0
    default_pulse_ms: 10
    allow_enable: true
  c_flipper_left_main:
    number: 3208-4  # again, these numbers will probably be different for you
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 3208-5  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    default_pulse_ms: 20
    number: 3208-1
  c_flipper_right_hold:
    number: 3208-3
    allow_enable: true

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    #enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    #enable_events: machine_reset_phase_3

ball_devices:
    bd_plunger:
      mechanical_eject: true
      ball_switches: s_shooter_lane
    bd_trough:
      ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
      eject_coil: c_trough_eject
      tags: trough, home, drain
      jam_switch: s_trough_jam
      eject_coil_jam_pulse: 15ms
      debug: true

autofire_coils:
  ac_slingshot_left:
    coil: c_left_slingshot
    switch: s_left_slingshot
  ac_slingshot_right:
    coil: c_right_slingshot
    switch: s_right_slingshot


slides: 
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL BITCH!
        font_size: 60
        color: red
      - type: rectangle
        width: 460
        height: 60
  attract_started: 
    widgets:
      - text: ATTRACT MODE
        type: text 

slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started


keyboard:
  z:
    switch: s_left_flipper
  "<":
    switch: s_right_flipper
  x:
    switch: s_trough1
    toggle: true
  c:
    switch: s_trough2
    toggle: true
  v:
    switch: s_trough3
    toggle: true
  b:
    switch: s_trough4
    toggle: true
  n:
    switch: s_trough5
    toggle: true
  m: 
    switch: s_trough6
    toggle: true
  s:
    switch: s_start_button
  p:
    switch: s_plunger_lane
  o:
    switch: s_right_outlane

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3

modes: 
  - base