#config_version=5

lights:
  GI_light1:
    number: playfield-1-1
  GI_light2:
    number: playfield-1-2
  GI_light3:
    number: playfield-1-3
  GI_light4: 
    number: playfield-1-4
  GI_light5:
    number: playfield-1-5
  GI_light6:
    number: playfield-1-6
  GI_light7:
    number: playfield-1-7
  GI_light8:
    number: playfield-1-8
  GI_light9:
    number: playfield-1-9
  l_xenos_x:
    number: playfield-1-10
    tags: xenos_letter
  l_xenos_e:
    number: playfield-1-11
    tags: xenos_letter
  l_xenos_n:
    number: playfield-1-12
    tags: xenos_letter
  l_xenos_o:
    number: playfield-1-13
    tags: xenos_letter
  l_xenos+s:
    number: playfield-1-14
    tags: xenos_letter
  l_lockdown_bar:
    number: playfield-1-16
    tags: xenos_letter
