#config_version=6


modes: 
  - base
  #- high_score
  - xenos
  - nurgle
  - khorne
  - tzeench
  - slannesh
  - warp_qualify
  - ball_save
  - mission_select
  - mechanicus_qualifier
  - necrons
  - mystery_mode
  #- WeaponsBank
  - titan_multiball
  #- waagh_multiball
  #- inquisition_multiball
  #- horus
  - tilt  
  #- bonus
  #- necron_lock
  #- necron_lock_qualified
  #- necron_multiball
  - gorkmorkrollovers
  - waagh_qualifier
  - waagh_multiball
  - skillshot
  #- super_skillshot
