#config_version=5
player_vars:
  xenos_available:
    initial_value: 0
  xenos_earned:
    initial_value: 0
  bonus_switches:
    initial_value: 0
  bonus_holy_relics:
    initial_value: 0
  bonus_warp_jumps:
    initial_value: 0
  bonus_modes_started:
    initial_value: 0
  pv_warp_mode_counter:
    initial_value: 3
  