#config_version=6

sounds:
  sound_slinghit:
    file: Kicker_bolter.wav
    bus: effects
    #priority: 50
    max_queue_time: None
  sound_scoop:
    file: scoop_eject.wav
    bus: effects
  music_warp_traveler:
    file: Warp Traveler.wav
    #bus: music
  music_emporer:
    file: The Emperor of Mankind.wav
    #bus: music
  #xenos_spotted:
   # file: xenos-spotted.wav
    #bus: voice
  lazgun:
    file: lazgun.wav
    bus: effects
    #priority: 50
    max_queue_time: None 
  door_open:
    file: sfx-door-open.wav
    bus: effects
    #priority: 50
    max_queue_time: None