#config_version=5

sounds:
  sound_slinghit:
    file: Kicker_bolter.wav
    track: sfx
    #priority: 50
    max_queue_time: None
  sound_scoop:
    file: scoop_eject.wav
    track: sfx
  music_warp_traveler:
    file: Warp Traveler.wav
    track: music
  music_emporer:
    file: The Emperor of Mankind.wav
  xenos_spotted:
    file: xenos-spotted.wav
    track: voice
  lazgun:
    file: lazgun.wav
    track: sfx
    #priority: 50
    max_queue_time: None 
  door_open:
    file: sfx-door-open.wav
    track: sfx
    #priority: 50
    max_queue_time: None