#config_version=5

sounds:
  sound_slinghit:
    file: Kicker_bolter.wav
    track: sfx
    priority: 50
    max_queue_time: None
  sound_scoop:
    file: scoop_eject.wav
    track: sfx
  music_warp_traveler:
    file: Warp Traveler.wav
    track: music
  xenos_spotted:
    file: xenos-spotted.wav
    track: voice
  sound_spinner1: 
    file: lazgun.wav
    track: sfx


  
