#config_version=6

switches:
  s_autoplunger:
    number: 3208-7
  s_trough5:
    number: 3208-6
  s_trough4:
    number: 3208-5
  s_trough3:
    number: 3208-4
  s_trough2:
    number: 3208-3
  s_spinner:
    number: 3208-1
    type: "NC"
    debounce: quick
  s_trough_jam:
    number: 3208-0
    type: "NC"
  s_trough1:
    number: 3208-2
  s_right_outlane:
    number: 3208-16
    #tags: playfield_active
  s_right_inlane:
    number: 3208-21
    #tags: playfield_active

  s_right_EOS:
    number: 3208-22
  s_left_EOS:
    number: 3208-20
  s_left_inlane:
    number: 3208-18
  s_left_outlane: 
    number: 3208-19

#  s_lower_bigtarget:
 #   number: 3208-16
  s_upper_bigtarget:
    number: 3208-29
  s_trough6:
    number: 3208-17
    type: "NC"
  s_left_slingshot: 
    number: 3208-21
  s_right_slingshot: 
    number: 3208-23
  s_pop_left:
    number: 3208-19
  s_pop_right:
    number: 3208-12
  s_pop_center:
    number: 3208-13
  s_rollover_gork:
    number: 3208-10
  s_rollover_mork: 
    number: 3208-11
  s_upperscoop:
    number: 3208-18
  s_right_flipper:
    number: 32082-11
    tags: right_flipper
  s_start_button:
    number: 32082-12
    tags: start
  s_left_flipper: 
    number: 32082-15
    tags: left_flipper
  s_tiltbob: 
    number: 3208-27
  s_xenos_x:
    number: 32082-4
  s_xenos_e:
    number: 32082-3
  s_xenos_n:
    number: 32082-2
  s_xenos_o:
    number: 32082-1
  s_xenos_s:
    number: 32082-0
  s_kickback1:
    number: 32082-7
  s_upperflipper_eos:
    number: 32082-6
    type: "NC"
  s_disk_backtarget:
    number: 32082-5
  s_droptarget_down:
    number: 3208-25
    debounce: normal
  s_droptarget_lock:
    number: 32082-14
  s_left_ramp: 
    number: 32082-23
    type: "NC"
  s_right_ramp:
    number: 32082-21
    type: "NC"
  s_unused:
    number: 32082-20
    type: "NC"
  s_scoop:
    number: 32082-19
    type: "NC"   
  s_3bank_home:
    number: 32082-6
  s_3bank_away:
    number: 32082-5
  s_tilt_bob:
    number: 3208-26
    tags: tilt_warning
     
  s_droptarget_opto:
    number: 32082-8
  s_upperleft_flipper:
    number: 3208-12
  s_left_orbit: 
    number: 32082-31
  s_3bank_top:
    number: 32082-0
  s_3bank_mid:
    number: 32082-1
  s_3bank_bottom:
    number: 32082-2
  s_right_orbit: 
    number: 32082-3
  s_left_deadend:
    number: 32082-4