#config_version=6

mode: 
  start_events: ModeSelect_khorne_selected
  stop_events: timer_khorne_mode_timer_complete
  priority: 200 

#stage 1
#Two Ramps are like make each ramp 3 times to light super jackpot and relight all major shots 
#hit as many of the major shots before scoring super jackpot at the scoop
# 

counter: 
    center_ramp:
        count_events: center_ramp_shot_hit
        starting_count: 0
        count_interval: 1
        count_complete_value: 3
    left_ramp:
        count_events: left_ramp_shot_hit
        starting_count: 0
        count_interval: 1
        count_complete_value: 3


timers:
    khorne_mode_timer: 
        start_value: 60 # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true

shots:
    left_ramp_shot:
        switch: 
    center_ramp_shot: 
        switch: 



shot_groups: 
    
    

shot_profiles: 
  

show_player:
    ModeSelect_khorne_selected:
    #light both ramp shots