#config_version=6

mode: 
  start_events: mission_select_khorne_selected
  stop_events: timer_khorne_mode_timer_complete
  priority: 200 

#stage 1
#Two Ramps are like make each ramp 3 times to light super jackpot and relight all major shots 
#hit as many of the major shots before scoring super jackpot at the upper vuk
# 

#Khorne - The Blood God (Number 8):

counters: 
    center_ramp:
        count_events: center_ramp_shot_hit
        starting_count: 0
        count_interval: 1
        count_complete_value: 3


timers:
    khorne_mode_timer: 
        start_value: 60 # seconds
        end_value: 0
        direction: down 
        tick_interval: 1s
        restart_on_complete: false
        start_running: true

shot_profiles:
    khorne_ramp_profile:
        states:
            - name: unlit
              show: "off"
            - name: lit
              show: "flash"
            - name: complete
              show: "on"
        loop: false

    khorne_major_shot_profile:
        states:
            - name: unlit
              show: "off"
            - name: lit
              show: "flash"
            - name: hit
              show: "on"
        loop: true

    khorne_super_jackpot_profile:
        states:
            - name: unlit
              show: "off"
            - name: lit
              show: "pulse_fast"
            - name: collected
              show: "on"
        loop: false

shots:
    khorne_center_ramp_shot:
        switch: s_center_ramp
        profile: khorne_ramp_profile
        start_enabled: false
        show_tokens:
            led: l_center_ramp_arrow
            color: red

    khorne_left_loop_shot:
        hit_events: base_innerloop_sequence_left_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        show_tokens:
            led: l_left_innerloop_arrow
            color: red

    knorne_right_loop_shot:
        hit_events: base_innerloop_sequence_right_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        show_tokens: 
            led: l_right_innerloop_arrow
            color: red

    khorne_left_orbit_shot:
        switch: s_left_orbit
        profile: khorne_ramp_profile
        start_enabled: false
        show_tokens:
            led: l_left_ramp_arrow
            color: red

    khorne_right_orbit_shot:
        switch: s_right_orbit
        profile: khorne_major_shot_profile
        start_enabled: false
        show_tokens:
            led: l_right_orbit_arrow
            color: red

    khorne_super_jackpot_shot:
        switch: s_jackpot_vuk
        profile: khorne_super_jackpot_profile
        start_enabled: false
        show_tokens:
            led: l_jackpot_arrow
            color: red

    khorne_ricochet_loop_shot:
        hit_events: khorne_ricochet_sequence_right_hit
        profile: khorne_major_shot_profile
        start_enabled: false
        show_tokens: 
            led: l_nurgle2
            color: red



sequence_shots: 
  khorne_left_loop_sequence:
    switch_sequence: s_innerloop_left, s_innerloop_right
  khorne_right_loops_sequence: 
   switch_sequence: s_innerloop_right, s_innerloop_left
  khorne_ricochet_sequence_right:
    switch_sequence: s_snikt_target, s_innerloop_right, s_innerloop_left
    sequence_timeout: 2s
#This will enable stages 1 -3 for the mode.
shot_groups:

    khorne_stage_one_one:
        shots: khorne_right_orbit_shot, khorne_left_orbit_shot
        enable_events: mission_select_khorne_selected
        reset_events: 
        disable_events: khorne_stage_one_one_hit #this will need to trigger after lightshow after stage one is hit
    khorne_stage_one_two: 
        shots: khorne_ricochet_loop, knorne_center_ramp, knorne_right_loop_shot, knorne_left_loop_shot, khorne_super_jackpot_shot
        enable_events: khorne_stage_one_one_hit #this will need to trigger after lightshow after stage one is hit
        
    knorne_stage_two_one:
        shots: khorne_right_orbit_shot, khorne_left_orbit_shot
        enable_events: khorne_stage_one_two_comeplete
        reset_events: 
        disable_events: khorne_stage_one_two_complete #this will need to trigger after lightshow after stage one is hit

    knorne_stage_two_two:
        shots: knorne_stage_two_one_complete
        enable_events: knorne_stage_two_one_complete #this will need to trigger after lightshow after stage one is hit


    knorne_stage_three: #the final stage should be all shots are lit, hitting any five shots will light super JP, however hitting a lit shot will unlight it and light other unlit shots 
    #meaning you can keep hitting shots indefinitely until you score the super JP or the timer expires. 
        shots:
        enable_events: knorne_stage_two_two_complete #this will need to trigger after lightshow after stage one is hit
        reset_events:




    # khorne_left_spinner_shot:
    #     switch: s_left_spinner
    #     profile: khorne_major_shot_profile
    #     show_tokens:
    #         led: l_left_spinner_arrow
    #         color: red

    # khorne_right_spinner_shot:
    #     switch: s_right_spinner
    #     profile: khorne_major_shot_profile
    #     show_tokens:
    #         led: l_right_spinner_arrow
    #         color: red

    # khorne_center_spinner_shot:
    #     switch: s_center_spinner
    #     profile: khorne_major_shot_profile
    #     show_tokens:
    #         led: l_center_spinner_arrow
    #         color: red

    

# shot_groups:
#     major_shots:
#         shots: right_orbit_shot, left_spinner_shot, right_spinner_shot, center_spinner_shot

#     ramp_shots:
#         shots: center_ramp_shot, left_ramp_shot

variable_player:
    center_ramp_shot_hit:
        score: 5000
    left_ramp_shot_hit:
        score: 5000
    right_orbit_shot_hit:
        score: 7500
    left_spinner_shot_hit:
        score: 2500
    right_spinner_shot_hit:
        score: 2500
    center_spinner_shot_hit:
        score: 2500
    logicblock_center_ramp_complete:
        score: 25000
    logicblock_left_ramp_complete:
        score: 25000
    upper_vuk_shot_hit:
        score: 50000

event_player:
    logicblock_center_ramp_complete:
        - khorne_center_ramp_lit_up
        - major_shots_relit
    logicblock_left_ramp_complete:
        - khorne_left_ramp_lit_up
        - major_shots_relit
    upper_vuk_shot_hit:
        - khorne_super_jackpot_collected
        - khorne_major_shots_reset


    