#config_version=6

mode:
  start_events: start_mechanicus_mode
  stop_events: ModeSelect_item_selected, ModeSelect_item_cancelled
  code: mpf.modes.carousel.code.carousel.Carousel
  events_when_stopped: ModeSelect_item_selected
  game_mode: true
  priority: 501

mode_settings:
  selectable_items: 
    - khorne
    - nurgle
    - slannesh 
    - tzeench 
    - necrons
    - tyranids
    - backToTheFight
  select_item_events: s_start_button_active
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active

slide_player:
  mode_ModeSelect_started: ModeSelect
