#config_version=6

mode:
  start_events: multiball_lock_dreadnought_full
  stop_events: ball_will_end
  events_when_started: dreadnought_multiball_start
  events_when_stopped: 

  priority: 300


multiballs:
  dreadnought_multiball:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s # 20 seconds to shoot again
    ball_locks: bd_dreadnought
    start_events:
      - dreadnought_multiball_start
    stop_events:
      - dreadnought_multiball_stop
