#config_version=6




#triggering this mode will start up the muliball, 
# I need the gattling gun motor to start spinnning and the GI should flash along with it.
# It needs to be a big moment, His main eye should "Wake up", A voice line will go off, then after the voice line the motor will trigger and the balls will drop

#This mode should be about putting balls back into the dreadnought, that will reset the jackpot shots and boost base jackpot values
# Shooting 5 lit jackpots will light the super jackpot at the upper vuk

#FULL  BLINKY
mode:
  start_events: start_dreadnought_multiball
  stop_events: ball_will_end
  events_when_started: dreadnought_multiball_start
  events_when_stopped: 
  priority: 300


multiballs:
  dreadnought_multiball:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s # 20 seconds to shoot again
    ball_locks: bd_dreadnought
    start_events:
      - dreadnought_multiball_start
    stop_events:
      - dreadnought_multiball_stop

shots:
    dreadnought1:
        switch: s_nurgle_redcircle
        start_enabled: true
        enable_events:
        disable_events:
        restart_events: dreadnought_multiball_start

    dreadnought2:
        switch: s_nurgle_redcircle
        start_enabled: true
        enable_events:  
        disable_events:
        restart_events: dreadnought_multiball_start

    dreadnought3:
        switch: s_left_orbit
        enable_events: 
        disable_events:
        restart_events: dreadnought_multiball_start
        start_enabled: true
    dreadnought4: 
        hit_events: base_innerloop_left_hit
        enable_events:
        disable_events: 
        restart_events: dreadnought_multiball_start
        start_enabled: true
    dreadnought_super_jackpot:
        restart_events: enable_dreadnought_super_jackpot
        switch: s_jackpot_vuk
        start_enabled: 
    dreadnought_double_super_jackpot: 
        restart_events: enable_dreadnought_double_super_jackpot
        switch: s_jackpot_vuk
        start_enabled: false
    dreadnought_exterminatus_jackpot:
        restart_events: enable_dreadnought_exterminatus_jackpot
        switch: s_jackpot_vuk
        start_enabled: false 


counter:
    dreadnought_superjackpot:
        count_events:
        count_complete_value: 5
        disable_on_complete: true
        events_when_complete: enable_dreadnought_super_jackpot, enable_dreadnought_double_super_jackpot_counter
    dreadnought_double_super_jackpot:
        count_events:
        enable_events: enable_dreadnought_double_super_jackpot_counter
        count_complete_value: 5
        disable_on_complete: true
        events_when_complete: 
    dreadnought_exterminatus_jackpot:
        count_events:
        enable_events: enable_dreadnought_exterminatus_jackpot_counter
        count_complete_value: 5
        disable_on_complete: true




show_player: 
    #start dreadnought multiball show
    #set GI to Red
    mode_dreadnought_multiball_started:
        setGI:
            show_tokens: 
                led: GI
                color: red
   
sound_player:
    mode_dreadnought_multiball_started:
        404363:
            action: play
            volume: 1
            bus: voice
            ducking:
                bus: voice
                attack: 0.0 sec
                attenuation: 0
                release_point: 0.0 sec
                release: 0.0 sec

       
event_player:
     #Enable Cannon then disable cannon
    mode_dreadnought_multiball_start:
        - enable_gattling_cannon
        - disable_gattling_cannon|5s 