#config_version=6
##! mode: warp_qualify

mode:
  #this mode starts when the ball starts
  start_events: ball_started, mode_slannesh_stopped, mode_knorne_stopped, mode_nurgle_stopped, mode_tzeentch_stopped, multiball_waagh_multiball_ended 
  #stop_events: warp_qualify_stop, mode_slannesh_started, mode_knorne_started, mode_nurgle_started, mode_tzeentch_started,  waagh_multiball_mode_start
  priority: 200

shots:
  warp_outlane_left:
    switch: s_left_outlane
    profile: inlane_lane_profile
    show_tokens:
      led: l_warp_w
  warp_inlane_left:
    switch: s_left_inlane
    profile: inlane_lane_profile
    show_tokens:
      led: l_warp_a
  warp_inlane_right:
    switch:  s_right_inlane
    profile: inlane_lane_profile
    show_tokens:
      led: l_warp_r
  warp_outlane_right:
    switch:  s_right_outlane
    profile: inlane_lane_profile
    show_tokens:
      led: l_warp_p


shot_groups:
  inlane_lane_group:
    shots: warp_inlane_left, warp_inlane_right, warp_outlane_right, warp_outlane_left
    reset_events: inlane_lane_group_lit_complete
    rotate_left_events: s_left_flipper_active
    rotate_right_events: s_right_flipper_active
   
shot_profiles:
  inlane_lane_profile:
    states:
      - name: unlit
        show: off
      - name: lit
        show: on

variable_player:
  inlane_lane_group_lit_complete:
    score: 10000
    bonus_multiplier: 1


event_player:
    inlane_lane_group_lit_complete:
        #starting the Mystery Mode for the scoop hold
        - enable_mystery
        - start_warp_hurryup
 
show_player: 
  reset_warp_lights:
    light_xenos_letter:
      priority: 10
      show_tokens:
        letter_made_led: lane
        letter_made_color: Purple
        letter_made_final_color: 000000    

