#config_version=5
mode:
  start_events: start_necron_lock_qualified 
  stop_events: start_necron_multiball
  priority: 100

counters:
  necron_lockup_qualified:
    count_events: s_droptarget_down_active
    starting_count: 0
    count_interval : 1
    direction: up
    count_complete_value: 1
    events_when_complete: 
      - start_necron_multiball
    disable_on_complete: true

    